fix: Footer and Email Header

diff --git a/.husky/post-commit b/.husky/post-commit
--- a/.husky/post-commit
+++ b/.husky/post-commit
@@ -11,10 +11,16 @@ git push -u origin ||
 
 echo "🗑️ Removing temp build files"
 
-rm -r build || 
+rm -rf build .next || 
 (
     echo '🔐 Failed to remove the required directory. Please update ownership permissions and then retry!';
     false;
 )
 
-echo '🎉 Done!'
+echo '🎉 Done! Restarting the Dev Server'
+
+yarn dev || 
+(
+    echo '😵 Failed to restart the dev server. Please check the logs and then retry!';
+    false;
+)
